# ChatLlmRecognition.action
# Goal
string request        # リクエストメッセージ
string room_name      # 部屋名指定
bool is_service       # Feedbackを送るかどうか
---
# Result
string result         # 返答メッセージ
float64 elapsed_time  # 返答まで何秒かかったか
---
# Feedback
string wip_result     # 途中経過のメッセージ
bool end_flag         # 途中経過の送信がが終了したかどうか