# Goal
string request    # "record", "pause", "resume", "save", "delete"
---
# Result
bool success      # true if the action was successful, false otherwise
string message    # "succeded", "failed", "in_progress", "not_found"
---
# Feedback
string status     # "recording", "paused"
