# Request

# Array of AttachedCollisionObjects to be attached to or detached from the robot
moveit_msgs/AttachedCollisionObject[] attached_objects

# Operation to apply to all attached objects
# 0: ADD (attach), 1: REMOVE (detach)
uint8 operation

---
# Result

# Request execution result
bool success

# Detailed result or error message
string message