# TF frame names used to determine the pose of each CollisionObject
string[] target_frames

# CollisionObjects to be applied to the MoveIt Planning Scene.
# The pose of each object is updated using the corresponding TF frame.
moveit_msgs/CollisionObject[] collision_objects

# Operation to apply to all collision objects
# 0: ADD, 1: REMOVE, 2: APPEND, 3: MOVE
uint8 operation

---
# Request execution result
bool success

# Detailed result or error message
string message